name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up -d
          echo "⏳ Waiting for containers to be healthy..."
          docker compose ps
          docker compose logs web

      - name: Run test inside web container
        run: |
          docker compose run --rm web curl -f http://localhost:5000/api/users

      - name: Capture logs if test fails
        if: failure()
        run: docker compose logs

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down

